Feature/銀行和分行資料定期更新
5fpro/demeter pull request #1
Opened 2020-05-13 09:22 UTC by telsaiori

https://github.com/5fpro/bznk/issues/549

2020-05-13 11:40 UTC, telsaiori commented
@marsz 
這個好了，麻煩review。

2020-05-17 08:58 UTC, marsz reviewed
@telsaiori reviewed

2020-05-17 08:58 UTC, marsz commented on app/controllers/api/banks_controller.rb
> +      render json: @branches
我想要吐出來的資料去掉 id, created_at, updated_at 這三個欄位, branch 追加去掉 bank_id
就是對外想要去掉資料庫的內容，僅吐出公開性資料
然後這邊你可以順便試試看用 jbuilder 的 view
bznk 專案內有範例可以參考

2020-05-17 08:58 UTC, marsz requested changes
@telsaiori

2020-05-17 21:05 UTC, telsaiori commented on app/controllers/api/banks_controller.rb
> +      render json: @branches
@marsz 
我改用jbuilder了。不過光就現在的情形我看不出來用jbuilder會有什麼優點？

2020-05-18 14:45 UTC, marsz commented
@telsaiori API 這邊的行為需要調整一下
分行不可能全撈
應該是先撈銀行出來，再看要從哪個銀行去撈該銀行下的分行資料:

GET /banks
GET /banks/:bank_code/branches

另外就是分行的每筆資料我想要這樣定義
```json
{
  branch_code: '分行代碼',
  bank_branch_code: '銀行+分行代碼(共七碼)',
  address: '分行地址',
  name: '分行名稱'
}
```

2020-05-21 10:46 UTC, telsaiori commented
@marsz 
改好囉，再麻煩一下。

2020-05-21 11:05 UTC, marsz requested changes
@telsaiori 已 review ，改完就可以 merge 了
順便在 README.md 補一下執行抓取的方式

2020-05-21 11:05 UTC, marsz commented on app/views/api/base/branches.jbuilder
> +  json.bank_branch_code branch.bank.code + branch.code
code = nil 時這裡就會噴了，用 "#{}#{}" 的方式吧

2020-05-21 12:14 UTC, merged